[profile.dev]
panic = "abort"

[profile.release]
codegen-units = 1 # better optimizations
lto = true # better optimizations
panic = "abort"

[workspace]
members = [
  "rtfm",
  "rtfm/macros",
]

[patch.crates-io]
nc = { git = "https://github.com/chemicstry/nc", branch = "fix_rt_sigprocmask" }
